SELECT EC_SECT.TIME_RECORD AS COLLEGE_RECORD
	 , EC_SECT.COLLEGE_CODE
	 , MC.COLLEGE_NAME
	 , EC_SECT.SECTION_CODE
     , EC_SECT.SECTION_NAME
	 , 1900 YEAR_CODE
     , COUNT(EP.TIME_RECORD) AS RANKING
	 , EP.PLAYER_CODE
	 , MP.PLAYER_NAME
	 , EP.TIME_RECORD AS PLAYER_RECORD
  FROM (SELECT EC.COLLEGE_CODE
             , EC.TIME_RECORD
             , EC.YEAR_CODE
             , sect.SECTION_CODE
             , sect.SECTION_NAME
          FROM d_entry_colleges AS EC
             , sections AS sect
         WHERE EC.YEAR_CODE = 1900) AS EC_SECT
       LEFT JOIN (SELECT * 
		            FROM d_entry_players AS EP
				   WHERE EP.YEAR_CODE = 1900) AS EP
       ON EC_SECT.COLLEGE_CODE = EP.COLLEGE_CODE
       AND EC_SECT.SECTION_CODE = EP.SECTION_CODE
       LEFT JOIN (SELECT *
	 			    FROM d_entry_players AS EP2
   				   WHERE EP2.YEAR_CODE = 1900) AS EP2
   	   ON EP.TIME_RECORD >= EP2.TIME_RECORD
   	   AND EP.SECTION_CODE = EP2.SECTION_CODE
   	   LEFT JOIN m_colleges AS MC
   	   ON EC_SECT.COLLEGE_CODE = MC.COLLEGE_CODE
   	   LEFT JOIN m_players AS MP
   	   ON EP.PLAYER_CODE = MP.PLAYER_CODE
 GROUP BY EC_SECT.TIME_RECORD
        , EC_SECT.SECTION_NAME
		, EC_SECT.SECTION_CODE]
		, EP.YEAR_CODE
		, EP.SECTION_CODE
		, EP.COLLEGE_CODE
		, MC.COLLEGE_NAME
		, EP.TIME_RECORD
 ORDER BY EC_SECT.TIME_RECORD
        , EC_SECT.COLLEGE_CODE
		, EC_SECT.SECTION_CODE
        , EP.TIME_RECORD